In [2]:
# Libraries

import numpy as np
import pandas as pd

In [5]:
# Importing the file

file = pd.read_csv(r'D:\ML\UCI_data.csv',sep=',')
print(file.head(5))

   6  148  72  35    0  33.6  0.627  50  1
0  1   85  66  29    0  26.6  0.351  31  0
1  8  183  64   0    0  23.3  0.672  32  1
2  1   89  66  23   94  28.1  0.167  21  0
3  0  137  40  35  168  43.1  2.288  33  1
4  5  116  74   0    0  25.6  0.201  30  0


In [162]:
# Dividing the data into x features and y target

x=file.iloc[:,0:7]
y=file.iloc[:,8:]

In [ ]:
print(x.head(5))

In [ ]:
print(y.head(5))

In [ ]:
# Data Normalization

from sklearn import preprocessing
normalized_x = preprocessing.normalize(x)
print(normalized_x)

In [ ]:
# Data standardization

from sklearn import preprocessing
standardized_x = preprocessing.scale(x)
print(standardized_x)

In [ ]:
# Feature selection

from sklearn import metrics
from sklearn.ensemble import ExtraTreesClassifier
model = ExtraTreesClassifier()
model.fit(x,y)
print(model.feature_importances_)

In [ ]:
# Recurssive Feature selection

from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()

rfe=RFE(model,3)
rfe.fit(x,y)

print(rfe.support_)
print(rfe.ranking_)

In [163]:
# Logistic regression 

from sklearn.linear_model import LogisticRegression
from sklearn import metrics

model = LogisticRegression()
model.fit(x,y)

expected=y
predicted=model.predict(x)

print(model.score(x,y))
print("\n",metrics.confusion_matrix(expected,predicted))
print(metrics.classification_report(expected,predicted))

0.7770534550195567

 [[449  51]
 [120 147]]
             precision    recall  f1-score   support

          0       0.79      0.90      0.84       500
          1       0.74      0.55      0.63       267

avg / total       0.77      0.78      0.77       767



C:\Users\athiq.ahmed\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [164]:
# Naive Bayes

from sklearn.naive_bayes import GaussianNB
from sklearn import metrics

model = GaussianNB()
model.fit(x,y)

expected = y
predicted = model.predict(x)

print(model.score(x,y))
print("\n",metrics.confusion_matrix(expected,predicted))
print(metrics.classification_report(expected,predicted))

0.7666232073011734

 [[429  71]
 [108 159]]
             precision    recall  f1-score   support

          0       0.80      0.86      0.83       500
          1       0.69      0.60      0.64       267

avg / total       0.76      0.77      0.76       767



C:\Users\athiq.ahmed\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [165]:
# KNN (K-nearest neighbors)

from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics

model = KNeighborsClassifier(n_neighbors=3)
model.fit(x,y)

expected = y
predicted = model.predict(x)

print(model.score(x,y))
print(metrics.confusion_matrix(expected,predicted))
print(metrics.classification_report(expected,predicted))

0.8396349413298566
[[460  40]
 [ 83 184]]
             precision    recall  f1-score   support

          0       0.85      0.92      0.88       500
          1       0.82      0.69      0.75       267

avg / total       0.84      0.84      0.84       767



C:\Users\athiq.ahmed\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:7: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  import sys


In [166]:
# Decision tree model

from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics

model = DecisionTreeClassifier()
model.fit(x,y)

expected = y
predicted = model.predict(x)

print(model.score(x,y))
print("\n",metrics.confusion_matrix(expected,predicted))
print(metrics.classification_report(expected,predicted))

1.0

 [[500   0]
 [  0 267]]
             precision    recall  f1-score   support

          0       1.00      1.00      1.00       500
          1       1.00      1.00      1.00       267

avg / total       1.00      1.00      1.00       767



In [167]:
# Support vector machine

from sklearn.svm import SVC
from sklearn import metrics

model = SVC()
model.fit(x,y)

expected = y
predicted = model.predict(x)

print(model.score(x,y))
print("\n",metrics.confusion_matrix(expected,predicted))
print(metrics.classification_report(expected,predicted))

1.0

 [[500   0]
 [  0 267]]
             precision    recall  f1-score   support

          0       1.00      1.00      1.00       500
          1       1.00      1.00      1.00       267

avg / total       1.00      1.00      1.00       767



C:\Users\athiq.ahmed\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [169]:
# How to Optimize Algorithm Parameters

import numpy as np
from sklearn.linear_model import Ridge
from sklearn.grid_search import GridSearchCV
# prepare a range of alpha values to test
alphas = np.array([1,0.1,0.01,0.001,0.0001,0])
# create and fit a ridge regression model, testing each alpha
model = Ridge()
grid = GridSearchCV(estimator=model, param_grid=dict(alpha=alphas))
grid.fit(x, y)
print(grid)
# summarize the results of the grid search
print(grid.best_score_)
print(grid.best_estimator_.alpha)

GridSearchCV(cv=None, error_score='raise',
       estimator=Ridge(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001),
       fit_params={}, iid=True, n_jobs=1,
       param_grid={'alpha': array([1.e+00, 1.e-01, 1.e-02, 1.e-03, 1.e-04, 0.e+00])},
       pre_dispatch='2*n_jobs', refit=True, scoring=None, verbose=0)
0.2815814124730805
1.0


In [170]:
import numpy as np
from scipy.stats import uniform as sp_rand
from sklearn.linear_model import Ridge
from sklearn.grid_search import RandomizedSearchCV
# prepare a uniform distribution to sample for the alpha parameter
param_grid = {'alpha': sp_rand()}
# create and fit a ridge regression model, testing random alpha values
model = Ridge()
rsearch = RandomizedSearchCV(estimator=model, param_distributions=param_grid, n_iter=100)
rsearch.fit(x, y)
print(rsearch)
# summarize the results of the random parameter search
print(rsearch.best_score_)
print(rsearch.best_estimator_.alpha)

RandomizedSearchCV(cv=None, error_score='raise',
          estimator=Ridge(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001),
          fit_params={}, iid=True, n_iter=100, n_jobs=1,
          param_distributions={'alpha': <scipy.stats._distn_infrastructure.rv_frozen object at 0x0000001325DE39E8>},
          pre_dispatch='2*n_jobs', random_state=None, refit=True,
          scoring=None, verbose=0)
0.2815812755898256
0.9943446834978497


https://kukuruku.co/post/introduction-to-machine-learning-with-python-andscikit-learn/